version: '3.1'

services:
  web-app:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:9.6.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  # # for testing
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 4444:8080 # connect container 8080 with host 80
