version: '3.1'

services:
  # web:
  #   build: .
  #   command: npm run
  #   volumes:
  #     - .:/usr/app/
  #     - /usr/app/node_modules
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres-db
  postgres-db:
    image: postgres:9.6.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

  # # for testing
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
